sudo: required
services:
          - docker

before_install:
          - docker build -t akisoam199/docker-react -f Dockerfile.dev .

script:
          - docker run -e CI=true akisoam199/docker-react npm run test -- --coverage 

language: generic 
